{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-postpad
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/leightonpayne/postpad
  git_tag: 0.0.0.9000

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: getopt, knitr, rmarkdown
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-fs
    - r-purrr
    - r-readr
    - r-stringr

  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-fs
    - r-purrr
    - r-readr
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('postpad')"           # [not win]
    - "\"%R%\" -e \"library('postpad')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/leightonpayne/postpad
  license: MIT
  summary: Post-processing tools for exploring PADLOC results.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Type: Package
# Package: postpad
# Title: Post-processing tools for exploring PADLOC results
# Version: 0.0.0.9000
# Authors@R: person("Leighton", "Payne", , "leighton.payne@postgrad.otago.ac.nz", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2305-6827"))
# Description: Post-processing tools for exploring PADLOC results.
# License: MIT + file LICENSE
# Imports: cli, dplyr, fs, purrr, readr, stringr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# URL: https://github.com/leightonpayne/postpad
# BugReports: https://github.com/leightonpayne/postpad/issues
# Collate: 'utils.R' 'read-padlocout.R' 'sandbox.R' 'setup.R'
# Suggests: getopt, knitr, rmarkdown
# VignetteBuilder: knitr

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
